### ISSUE TITLE
Show moving gifs as thumbnails

### ISSUE THREAD

**Issue by devinmatte** [liam-middlebrook/gallery#18]
When uploading a `.gif`, the preview/thumbnail is a static image. I think it could improve gallery a bit if the thumbnail also moved. Not major, just a feature I'd like to see

**Comment by liam-middlebrook** [comment]
I'm not sure if you're interested in looking into implementing this idea also but if you are I'd recommend looking at [gallery/file_modules/gif.py](https://github.com/liam-middlebrook/gallery/blob/develop/gallery/file_modules/gif.py) and overriding the generate_thumbnail function from it's base class.
