### ISSUE TITLE
Folder Creation

### ISSUE THREAD

**Issue by Ha1fByte** [liam-middlebrook/gallery#6]
When you create folders there no redirect or confirmation of a folder being created you add a description, so you can accidentally create multiple folders without intending to.

**Comment by RamZallan** [comment]
We do show confirmation of folder creation, and let them add descriptions of folders. The reason we don't redirect is for when users need to create multiple different new folders.

**Comment by RamZallan** [comment]
Fixed in [this commit](https://github.com/liam-middlebrook/gallery/commit/2617c6457c06833f236f751021bfe5e641bb8c72)!
